# Use official Node.js image as the base image
FROM node:14-alpine

# Set working directory
WORKDIR /app/client

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install  

# Copy all files from the current directory to the working directory in the container
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the frontend application
CMD ["npm", "start"]
