version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend
      - mongo

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
