# Use official Node.js image as the base image
FROM node:14-alpine

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Set working directory
WORKDIR /app/backend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Rebuild bcrypt module
RUN npm rebuild bcrypt --build-from-source

# Copy all files from the current directory to the working directory in the container
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the backend application
CMD ["npm", "start"]